import { withPostHogConfig } from "@posthog/nextjs-config";
import { config as loadEnv } from "dotenv";
import type { NextConfig } from "next";

// Next only looks for .env beside the app, but this is a monorepo and the
// single source of truth lives at the repo root. In production Coolify injects
// the variables directly and no file is present.
loadEnv({ path: new URL("../../.env", import.meta.url).pathname, quiet: true });

/**
 * Identifies this build, and is used for nothing but the service worker.
 *
 * The worker caches under it and is registered under it, so a deploy — and
 * only a deploy — rotates its cache. Without that the cache name was a literal
 * `"v1"`: the worker's own bytes never changed from one deploy to the next, so
 * the browser never reinstalled it, and the `/offline` document precached on
 * somebody's first-ever visit went on being served months later — still
 * referencing script chunks that had long since been deleted. A worker that
 * can never be updated is the same trap the `Cache-Control` header below
 * avoids, one level down.
 *
 * A timestamp, because the build image has no git to take a SHA from. Set
 * `BUILD_ID` to pin it where a deploy already has an identifier worth reusing.
 */
const BUILD_ID = process.env.BUILD_ID?.trim() || `b${Date.now().toString(36)}`;

const config: NextConfig = {
  // Workspace packages ship TypeScript source rather than a build artefact,
  // so Next compiles them directly. This removes a per-package build step and
  // the ordering problems that come with it.
  transpilePackages: [
    "@voicemural/db",
    "@voicemural/llm",
    "@voicemural/shared",
    "@voicemural/workspace",
  ],
  serverExternalPackages: ["postgres"],
  // Inlined into the client bundle at build time, which is what makes the
  // registration URL in `components/service-worker.tsx` change per deploy.
  env: { NEXT_PUBLIC_BUILD_ID: BUILD_ID },
  // No `experimental.serverActions.bodySizeLimit` here even though chunks are
  // ~25 MB: that option governs Server Actions, and this app has none — every
  // mutation is a route handler, whose bodies Next does not cap. Configuring a
  // mechanism that does not exist only misleads the next reader.
  outputFileTracingRoot: new URL("../../", import.meta.url).pathname,
  async headers() {
    return [
      {
        // Files under public/ are served with a long max-age by default, and a
        // service worker cached for a year is a service worker that can never
        // be fixed. Browsers special-case this to a 24h cap, which is still a
        // day of serving whatever the last deploy shipped.
        source: "/sw.js",
        headers: [
          { key: "Cache-Control", value: "public, max-age=0, must-revalidate" },
          { key: "Service-Worker-Allowed", value: "/" },
        ],
      },
      {
        // Generated by scripts/generate-icons.mjs and named by size, so a
        // change to the mark changes nothing about these URLs — hence the
        // shorter window, and the revalidation that goes with it.
        source: "/icons/:file*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=86400, must-revalidate" },
        ],
      },
    ];
  },
};

// Uploading source maps needs a personal API key and a project id, and
// `withPostHogConfig` throws at config-load time when either is missing — which
// fails the build itself, not just the upload. PostHog is optional here (see
// .env.example), and a plain `docker build`, a contributor's checkout and a
// deploy that has not been given the keys all arrive without them, so the
// wrapper is applied only once both are present. Stack traces from such a build
// stay unminified in PostHog; the build succeeds.
const posthogPersonalApiKey = process.env.POSTHOG_API_KEY?.trim();
const posthogProjectId = process.env.POSTHOG_PROJECT_ID?.trim();

/**
 * An off switch that does not require surrendering the credentials.
 *
 * Unsetting the two variables above also disables the upload, but they are the
 * pair the rest of PostHog reads, so turning off one debugging convenience
 * would mean turning off the reporting it belongs to. This leaves them in
 * place and skips only the part that costs the build minutes of IO.
 */
const sourcemapsDisabled =
  process.env.POSTHOG_SOURCEMAPS?.trim().toLowerCase() === "false";

/**
 * Stop a failed source-map upload from failing the build.
 *
 * `withPostHogConfig` installs a `runAfterProductionCompile` hook that injects
 * chunk ids across the build output and then uploads it — on this app, 310 map
 * files and about 48 MB. Next treats a throw from that hook as a failed build,
 * so the upload holds a veto over every deploy.
 *
 * It used that veto on 20 Sep. `next build` had already printed `✓ Compiled
 * successfully`; then the build host's OOM killer fired mid-upload (`Out of
 * memory: Killed process ... (python)`, with no swap configured and ~2.8 GiB
 * free) and the deploy died with `Failed to run runAfterProductionCompile`.
 * The compiled application was fine and was thrown away regardless. A network
 * blip to PostHog produces the same outcome, which is easy to reproduce by
 * pointing `POSTHOG_HOST` at a closed port.
 *
 * Source maps only make a stack trace more legible after the fact. They are
 * not worth a production deploy, so a failure here is now a warning and the
 * build ships the artefact it already has.
 */
function surviveSourcemapFailure(wrapped: NextConfig): NextConfig {
  const tolerate = (resolved: NextConfig): NextConfig => {
    // The hook hangs off `compiler`, not the config root — see
    // `withCompilerConfig` in @posthog/nextjs-config.
    const upload = resolved.compiler?.runAfterProductionCompile;
    if (typeof upload !== "function") return resolved;

    return {
      ...resolved,
      compiler: {
        ...resolved.compiler,
        runAfterProductionCompile: async (metadata) => {
          try {
            await upload(metadata);
          } catch (error) {
            // Deliberately swallowed: see above. The build continues, and
            // stack traces for this release stay unminified in PostHog.
            console.warn(
              "[posthog] source-map upload failed; shipping the build without it.",
              error,
            );
          }
        },
      },
    };
  };

  // `withPostHogConfig` is TYPED as returning a NextConfig but actually returns
  // Next's other accepted shape, a `(phase, { defaultConfig })` function that
  // resolves the config later. Reading `.compiler` off it therefore finds
  // nothing, which is a silent no-op rather than a type error — so branch on
  // what is really there instead of on what the signature claims.
  if (typeof wrapped === "function") {
    const resolve = wrapped as unknown as (
      phase: string,
      context: { defaultConfig: NextConfig },
    ) => NextConfig | Promise<NextConfig>;

    return (async (phase: string, context: { defaultConfig: NextConfig }) =>
      tolerate(await resolve(phase, context))) as unknown as NextConfig;
  }

  return tolerate(wrapped);
}

export default posthogPersonalApiKey && posthogProjectId && !sourcemapsDisabled
  ? surviveSourcemapFailure(
      withPostHogConfig(config, {
        personalApiKey: posthogPersonalApiKey,
        projectId: posthogProjectId,
        host: process.env.POSTHOG_HOST,
        sourcemaps: {
          enabled: true,
          deleteAfterUpload: true,
        },
      }),
    )
  : config;
