import { readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { withPostHogConfig } from "@posthog/nextjs-config";
import { config as loadEnv } from "dotenv";
import type { NextConfig } from "next";

// Next only looks for .env beside the app, but this is a monorepo and the
// single source of truth lives at the repo root. In production Coolify injects
// the variables directly and no file is present.
loadEnv({ path: new URL("../../.env", import.meta.url).pathname, quiet: true });

/**
 * Identifies this build, and is used for nothing but the service worker.
 *
 * The worker caches under it and is registered under it, so a deploy — and
 * only a deploy — rotates its cache. Without that the cache name was a literal
 * `"v1"`: the worker's own bytes never changed from one deploy to the next, so
 * the browser never reinstalled it, and the `/offline` document precached on
 * somebody's first-ever visit went on being served months later — still
 * referencing script chunks that had long since been deleted. A worker that
 * can never be updated is the same trap the `Cache-Control` header below
 * avoids, one level down.
 *
 * A timestamp, because the build image has no git to take a SHA from. Set
 * `BUILD_ID` to pin it where a deploy already has an identifier worth reusing.
 */
const BUILD_ID = process.env.BUILD_ID?.trim() || `b${Date.now().toString(36)}`;

const config: NextConfig = {
  // Workspace packages ship TypeScript source rather than a build artefact,
  // so Next compiles them directly. This removes a per-package build step and
  // the ordering problems that come with it.
  transpilePackages: [
    "@voicemural/db",
    "@voicemural/llm",
    "@voicemural/shared",
    "@voicemural/workspace",
  ],
  serverExternalPackages: ["postgres"],
  // Inlined into the client bundle at build time, which is what makes the
  // registration URL in `components/service-worker.tsx` change per deploy.
  env: { NEXT_PUBLIC_BUILD_ID: BUILD_ID },
  // No `experimental.serverActions.bodySizeLimit` here even though chunks are
  // ~25 MB: that option governs Server Actions, and this app has none — every
  // mutation is a route handler, whose bodies Next does not cap. Configuring a
  // mechanism that does not exist only misleads the next reader.
  outputFileTracingRoot: new URL("../../", import.meta.url).pathname,
  async headers() {
    return [
      {
        // Files under public/ are served with a long max-age by default, and a
        // service worker cached for a year is a service worker that can never
        // be fixed. Browsers special-case this to a 24h cap, which is still a
        // day of serving whatever the last deploy shipped.
        source: "/sw.js",
        headers: [
          { key: "Cache-Control", value: "public, max-age=0, must-revalidate" },
          { key: "Service-Worker-Allowed", value: "/" },
        ],
      },
      {
        // Generated by scripts/generate-icons.mjs and named by size, so a
        // change to the mark changes nothing about these URLs — hence the
        // shorter window, and the revalidation that goes with it.
        source: "/icons/:file*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=86400, must-revalidate" },
        ],
      },
    ];
  },
};

// Uploading source maps needs a personal API key and a project id, and
// `withPostHogConfig` throws at config-load time when either is missing — which
// fails the build itself, not just the upload. PostHog is optional here (see
// .env.example), and a plain `docker build`, a contributor's checkout and a
// deploy that has not been given the keys all arrive without them, so the
// wrapper is applied only once both are present. Stack traces from such a build
// stay unminified in PostHog; the build succeeds.
const posthogPersonalApiKey = process.env.POSTHOG_API_KEY?.trim();
const posthogProjectId = process.env.POSTHOG_PROJECT_ID?.trim();

/** The trailer a bundler appends to a chunk to point at its source map. */
const SOURCE_MAPPING_URL = /^[ \t]*\/\/# sourceMappingURL=[^\r\n]*[ \t]*$/gm;

/**
 * Leaves the build output as a successful upload would have left it: no maps.
 *
 * Enabling the upload also turns on `productionBrowserSourceMaps`, and the
 * success path has posthog-cli delete the `.map` files (`--delete-after`)
 * before stripping the comments that point at them. Nothing does that when the
 * upload fails, so skipping this would ship ~300 maps that hand the whole
 * client source to anyone who opens devtools — a failed telemetry upload must
 * not publish the app's source. Deliberately allowed to throw: failing the
 * build is the right outcome if the maps cannot be removed.
 */
async function discardSourceMaps(distDir: string) {
  const entries = await readdir(distDir, {
    recursive: true,
    withFileTypes: true,
  });
  await Promise.all(
    entries.map(async (entry) => {
      if (!entry.isFile()) return;
      const file = join(entry.parentPath, entry.name);
      if (file.endsWith(".map")) return rm(file, { force: true });
      if (!file.endsWith(".js") && !file.endsWith(".css")) return;
      const source = await readFile(file, "utf8");
      const stripped = source.replace(SOURCE_MAPPING_URL, "");
      if (stripped !== source) await writeFile(file, stripped);
    }),
  );
}

/**
 * The upload runs as a `compiler.runAfterProductionCompile` hook that has no
 * error handling of its own, so anything it throws — a rejected key, a project
 * id that does not match it, a build container with no route to PostHog —
 * comes out of `next build` and fails the whole deploy, minutes in, after a
 * compile that succeeded. Error tracking is not worth a failed deploy, so the
 * hook is wrapped to warn and carry on.
 *
 * `withPostHogConfig` declares that it returns a `NextConfig`, but it actually
 * returns the function form that Next calls with the build phase — the hooks
 * only exist on what that call returns, hence the casts and the await. Calling
 * it rather than rebuilding its result is also what keeps the plugin's own
 * wiring intact; it warns if it is handed to a wrapper that drops it.
 */
type NextConfigFn = (
  phase: string,
  context: { defaultConfig: NextConfig },
) => Promise<NextConfig>;

function withSourcemapUpload(
  base: NextConfig,
  credentials: { personalApiKey: string; projectId: string },
): NextConfig {
  const withUpload = withPostHogConfig(base, {
    ...credentials,
    host: process.env.POSTHOG_HOST,
    sourcemaps: {
      enabled: true,
      deleteAfterUpload: true,
    },
  }) as unknown as NextConfigFn;

  const resilient: NextConfigFn = async (phase, context) => {
    const resolved = await withUpload(phase, context);
    const upload = resolved.compiler?.runAfterProductionCompile;
    if (!upload) return resolved;

    return {
      ...resolved,
      compiler: {
        ...resolved.compiler,
        runAfterProductionCompile: async (metadata) => {
          try {
            await upload(metadata);
          } catch (error) {
            const reason = error instanceof Error ? error.message : String(error);
            console.warn(
              `[posthog] source-map upload failed, continuing without it: ${reason}`,
            );
            await discardSourceMaps(metadata.distDir);
          }
        },
      },
    };
  };

  return resilient as unknown as NextConfig;
}

export default posthogPersonalApiKey && posthogProjectId
  ? withSourcemapUpload(config, {
      personalApiKey: posthogPersonalApiKey,
      projectId: posthogProjectId,
    })
  : config;
