"use client";

import { useCallback, useState } from "react";
import {
  DEBRIEF_QUESTIONS,
  STUDY_SCALE_MAX,
  itemsForPhase,
  type StudyItem,
  type StudyResponsePhase,
} from "@voicemural/shared";

/**
 * The study's own screens: one rating before a drive, three after it, and the
 * three spoken questions in between.
 *
 * WHY THEY EXIST. Pilot 01 measured only the system — latency, turn counts,
 * decline rate — and every one of those numbers was healthy on a drive that
 * left the participant waiting in silence with no way to tell working from
 * broken. Whether the system RELIEVED them is not derivable from the ledger.
 * It has to be asked, and it has to be asked in the two seconds either side of
 * a drive, or it will not be answered at all.
 *
 * DESIGNED FOR A PHONE IN A CRADLE, like everything else here: one row of
 * large targets, no typing, no scrolling to reach the answer, and every item
 * skippable by simply carrying on. A study instrument that makes somebody stop
 * and read is a study instrument that changes the thing it measures.
 */

async function record(body: {
  captureSessionId: string | null;
  phase: StudyResponsePhase;
  item: string;
  value: number;
}): Promise<void> {
  try {
    await fetch("/api/study/response", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ ...body, scaleMax: STUDY_SCALE_MAX }),
    });
  } catch {
    // A rating that does not reach the server is a missing cell in the
    // analysis. It is never worth interrupting a drive over.
  }
}

/** One 1–7 item as a row of targets. Answering twice corrects the answer. */
export function Scale({
  item,
  value,
  onPick,
}: {
  item: StudyItem;
  value: number | null;
  onPick: (value: number) => void;
}) {
  return (
    <fieldset className="w-full">
      <legend className="mb-2 text-sm text-white/70">{item.question}</legend>
      <div className="flex gap-1.5">
        {Array.from({ length: STUDY_SCALE_MAX }, (_, i) => i + 1).map((n) => (
          <button
            key={n}
            type="button"
            onClick={() => onPick(n)}
            aria-pressed={value === n}
            className={[
              "h-11 flex-1 cursor-pointer rounded-lg font-mono text-sm transition-colors",
              value === n
                ? "bg-white text-[var(--color-ink)]"
                : "bg-white/10 text-white/70 hover:bg-white/20",
            ].join(" ")}
          >
            {n}
          </button>
        ))}
      </div>
      <div className="mt-1 flex justify-between text-xs text-white/35">
        <span>{item.anchors[0]}</span>
        <span>{item.anchors[1]}</span>
      </div>
    </fieldset>
  );
}

/**
 * The pre item, shown before Record.
 *
 * The answer is held here until a drive exists to attach it to — a rating is
 * about a session, and the session id is generated by the recorder at the
 * moment of starting. `onAnswer` hands it up so the recorder can post it once
 * the drive has an id; answering is never a precondition for recording.
 */
export function PreDriveItem({ onAnswer }: { onAnswer: (item: string, value: number) => void }) {
  const [picked, setPicked] = useState<Record<string, number>>({});
  const items = itemsForPhase("pre");

  return (
    <div className="w-full max-w-md space-y-4 rounded-xl border border-line bg-white/[0.03] p-4">
      {items.map((item) => (
        <Scale
          key={item.key}
          item={item}
          value={picked[item.key] ?? null}
          onPick={(value) => {
            setPicked((prev) => ({ ...prev, [item.key]: value }));
            onAnswer(item.key, value);
          }}
        />
      ))}
      <p className="text-xs text-white/35">
        Before you start. One tap, or just press record — it is not required.
      </p>
    </div>
  );
}

/**
 * The debrief: three questions answered ALOUD, then the post ratings, then
 * done.
 *
 * The microphone is still open while this is on screen, which is the whole
 * point — `/study` promises these three questions after every drive and says
 * researchers read the answers, and until now they were asked after the
 * recording had already stopped. The window is marked on the session, so the
 * speech inside it is the debrief and everything outside it stays private.
 *
 * The ratings are on screen rather than spoken because a number read aloud is
 * a number the transcriber has to get right, and because the participant is by
 * definition no longer driving.
 */
export function DebriefPanel({
  captureSessionId,
  onDone,
}: {
  captureSessionId: string | null;
  onDone: () => void;
}) {
  const [picked, setPicked] = useState<Record<string, number>>({});
  const items = itemsForPhase("post");

  const pick = useCallback(
    (item: string, value: number) => {
      setPicked((prev) => ({ ...prev, [item]: value }));
      void record({ captureSessionId, phase: "post", item, value });
    },
    [captureSessionId],
  );

  return (
    <div className="w-full max-w-md space-y-5 rounded-xl border border-accent/30 bg-accent/5 p-4">
      <div>
        <p className="mb-1 font-medium">Still recording — say these out loud.</p>
        <ol className="space-y-2 text-sm text-white/70">
          {DEBRIEF_QUESTIONS.map((q, i) => (
            <li key={q} className="flex gap-3 leading-relaxed">
              <span className="shrink-0 font-mono text-white/30">{i + 1}</span>
              {q}
            </li>
          ))}
        </ol>
        <p className="mt-2 text-xs text-white/35">
          &ldquo;Nothing today&rdquo; is a fine answer. Complaints are the useful one.
        </p>
      </div>

      <div className="space-y-4 border-t border-line pt-4">
        {items.map((item) => (
          <Scale
            key={item.key}
            item={item}
            value={picked[item.key] ?? null}
            onPick={(value) => pick(item.key, value)}
          />
        ))}
      </div>

      <button
        type="button"
        onClick={onDone}
        className="w-full cursor-pointer rounded-lg bg-white px-4 py-3 font-medium text-[var(--color-ink)] hover:bg-white/90"
      >
        Done — stop recording
      </button>
    </div>
  );
}

/** Post one rating for a drive that now exists. Used for the held pre answer. */
export function recordStudyResponse(
  captureSessionId: string | null,
  phase: StudyResponsePhase,
  item: string,
  value: number,
): void {
  void record({ captureSessionId, phase, item, value });
}
